# Kafka ??
# ??? ??? ?? ?? ?? (??? ??)
kafka.bootstrap.servers=localhost:9092
# ?? ?? (??? ???? ??? ??? ??)
kafka.source.topic=test-topic
# ?? ?? (?? ??? ??? ??? ??)
kafka.sink.topic=franchise-top-stores-new
# ??? ?? ID (??? ??? ?? ???)
kafka.consumer.group=franchise-top-store-finder

# Schema Registry ??
# Confluent Schema Registry ?? ?? ?? (??? ??)
schema.registry.url=http://localhost:8081

# Flink ?? ??
# ??? ?? (? ??, ?? ??)
flink.window.size.seconds=10
# ????? ?? (??? ??, ?? ??? ?? ?? ?? ??)
flink.checkpoint.interval=60000
