# Kafka 서버 및 직렬화 설정
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.linger.ms=1
spring.kafka.producer.properties.batch.size=16384

# 스키마 레지스트리 URL
kafka.schema-registry-url=http://localhost:8081

# Kafka 토픽 이름
kafka.topic-name=test-topic

# Spring Kafka consumer 설정
spring.kafka.consumer.group-id=test-group

# 애플리케이션 데이터 설정
app.data.excel-path=./Dummy_data.xlsx
# 데이터 생성 주기 (밀리초 단위)
app.scheduler.fixed-rate=1000
# 데이터 생성 갯수
app.data.generate-count=1
